[package]
name = "adamv/simplecombat"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
BridgeNet2 = "ffrostflame/bridgenet2@1.0.0"
ByteNet = "ffrostfall/ByteNet@o.4.3"
#banner-notify = "yadbro/banner-notify@1.4.0"